name: Tests
on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'ui/packages/**'
      - 'ui/tests/**'
      - 'ui/package-lock.json'
      - '.github/workflows/electron-tests.yml'
  pull_request:
    paths:
      - 'ui/packages/**'
      - 'ui/tests/**'
      - 'ui/package-lock.json'
      - '.github/workflows/electron-tests.yml'

defaults:
  run:
    shell: 'bash'
    working-directory: 'ui'

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:main


  preload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:preload


  renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test:renderer


  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install --with-deps chromium
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e
        if: matrix.os == 'ubuntu-latest'
      - run: npm run test:e2e
        if: matrix.os != 'ubuntu-latest'
